baseURL = "https://andaze.github.io/WebCorporate/"

languageCode = "ja-JP"
DefaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true

title = "My New Hugo Site"
theme = "andaze"
disableKinds = ["taxonomy", "term"]
assetDir = "/assets"
canonifyurls = true

paginate = 2

[Languages]
[Languages.ja]
languageName = "JP"
weight = 1
languageCode = "ja-JP"
topCatchCopy = "経営視点でDXを加速させるプロ集団"
annotationDX = "※DX（デジタルトランスフォーメーション）…ITの浸透が、人々の生活をあらゆる面でより良い方向に変化させる"
footerFacebookTitle = "公式フェイスブック"
# footerPrivacyText = "プライバシーポリシー"
footerPrivacyText = "個人情報保護方針"
# footerSocialMediaPrivacyText = "ソーシャルメディアポリシー"
footerSocialMediaPrivacyText = "基本利用条件"
footerSiteMapText = "サイトマップ"

[Languages.en]
languageName = "EN"
weight = 2
languageCode = "en-us"
topCatchCopy = "A group of professionals who accelerate DX from a management perspective"
annotationDX = "*DX (Digital Transformation)...The penetration of IT changes people's lives for the better in every aspect"
# footerFacebookTitle = "Official Facebook"
footerFacebookTitle = "Official Twitter"
footerPrivacyText = "Privacy Policy"
# footerSocialMediaPrivacyText = "Social Media Policy"
footerSocialMediaPrivacyText = "Terms"
footerSiteMapText = "Site Map"

[params]
	JS = "/js/main.js"
	headerLogo = "img/yoko_c2.png"
	footerLogo = "img/yoko_2w.png"

	companyName = "アンダーズ株式会社"
[params.emailCredential]
	secureToken = "7670de06-d726-44e6-af6c-96dca7e5b64f"
	fromMail = "no-reply@andaze.com"
	bccMail = "nishidai@andaze.com"

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[[Languages.en.menu.main]]
name    ="Company"
url     ="company"
weight = 4
[[Languages.en.menu.main]]
name    ="Sustainability"
url     ="sustainability"
weight = 3
[[Languages.en.menu.main]]
name    = "Services"
url     = "services"
weight  = 2
[[Languages.en.menu.main]]
name    = "Why Choose Us"
url     = "reason"
weight  =  1
[[Languages.en.menu.main]]
name   = "Recruit"
url    = "https://www.andaze.com/job/en/"
weight = 7
identifier = "recruit"
post = "<i class='fi-xwsuxl-external-link-solid ml-1'></i>"
[[Languages.en.menu.main]]
name   = "Contact"
url    = "contact"
weight = 8



[[Languages.ja.menu.main]]
name    ="会社情報"
url     ="company"
weight = 4
[[Languages.ja.menu.main]]
name    ="サステナビリティ"
url     ="sustainability"
weight = 3
[[Languages.ja.menu.main]]
name    = "サービス"
url     = "services"
weight  = 2
[[Languages.ja.menu.main]]
name    = "選ばれる理由"
url     = "reason"
weight  =  1
[[Languages.ja.menu.main]]
name   = "採用情報"
url    = "https://www.andaze.com/job/ja/"
weight = 7
post = "<i class='fi-xwsuxl-external-link-solid ml-1'></i>"
identifier = "recruit"
[[Languages.ja.menu.main]]
name   = "お問い合わせ"
url    = "contact"
weight = 8
