baseURL = "https://andaze.github.io/WebCorporate/"

languageCode = "ja-JP"
DefaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true

title = "My New Hugo Site"
theme = "andaze"
disableKinds = ["taxonomy", "term"]
assetDir = "/assets"
canonifyurls = true

paginate = 2

[Languages]
[Languages.ja]
languageName = "JP"
weight = 1
languageCode = "ja-JP"
footerFacebookTitle = "公式フェイスブック"
footerPrivacyText = "プライバシーポリシー"
footerSocialMediaPrivacyText = "ソーシャルメディアポリシー"
footerSiteMapText = "サイトマップ"

[Languages.en]
languageName = "EN"
weight = 2
languageCode = "en-us"
footerFacebookTitle = "Official Facebook"
footerPrivacyText = "Privacy Policy"
footerSocialMediaPrivacyText = "Social Media Policy"
footerSiteMapText = "Site Map"

[params]
	JS = "/js/main.js"
	headerLogo = "img/yoko_c2.png"
	footerLogo = "img/yoko_2w.png"

	companyName = "アンダーズ株式会社"
[params.emailCredential]
	host = "smtp.elasticemail.com"
	userName = "nishidai@andaze.com"
	password = "AFA8942399E3F398BC2A88AC8589D21AD176"
	fromMail = "no-reply@andaze.com"
	bccMail = "nishidai@andaze.com"
	#secureToken = "27f56ad9-9d89-41d1-bc9d-41f72ebaf0a7"

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[[Languages.en.menu.main]]
name    ="company"
url     ="company"
weight = 1
[[Languages.en.menu.main]]
name    = "services"
url     = "services"
weight  = 2
[[Languages.en.menu.main]]
name    = "reason"
url     = "reason"
weight  =  3
[[Languages.en.menu.main]]
name   = "casestudy"
url    = "casestudy"
weight = 4
[[Languages.en.menu.main]]
name   = "solution"
url    = "solution"
weight = 5
[[Languages.en.menu.main]]
name   = "news"
url    = "news"
weight = 6
[[Languages.en.menu.main]]
name   = "recruit"
url    = "https://www.andaze.com/en/job/"
weight = 7
[[Languages.en.menu.main]]
name   = "contact"
url    = "contact"
weight = 8



[[Languages.ja.menu.main]]
name    ="会社情報"
url     ="company"
weight = 1
[[Languages.ja.menu.main]]
name    = "サービス"
url     = "services"
weight  = 2
[[Languages.ja.menu.main]]
name    = "理由"
url     = "reason"
weight  =  3
[[Languages.ja.menu.main]]
name   = "ケーススタディ"
url    = "casestudy"
weight = 4
[[Languages.ja.menu.main]]
name   = "解決方法"
url    = "solution"
weight = 5
[[Languages.ja.menu.main]]
name   = "ニュース"
url    = "news"
weight = 6
[[Languages.ja.menu.main]]
name   = "採用情報"
url    = "https://www.andaze.com/ja/job/"
weight = 7
target = "_blank"
[[Languages.ja.menu.main]]
name   = "お問い合わせ"
url    = "contact"
weight = 8
