baseURL = "https://andaze.github.io/WebCorporate/"

languageCode = "ja-JP"
DefaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true

title = "My New Hugo Site"
theme = "andaze"
disableKinds = ["taxonomy", "term"]
assetDir = "/assets"
publishDir = "docs"
canonifyurls = true

[Languages]
[Languages.ja]
languageName = "JP"
weight = 1
languageCode = "ja-JP"
footerFacebookTitle = "公式フェイスブック"
footerPrivacyText = "プライバシーポリシー"
footerSocialMediaPrivacyText = "ソーシャルメディアポリシー"
footerSiteMapText = "サイトマップ"

[Languages.en]
languageName = "EN"
weight = 2
languageCode = "en-us"
footerFacebookTitle = "Official Facebook"
footerPrivacyText = "Privacy Policy"
footerSocialMediaPrivacyText = "Social Media Policy"
footerSiteMapText = "Site Map"

[params]
	JS = "/js/main.js"
	headerLogo = "img/yoko_c2.png"
	footerLogo = "img/yoko_2w.png"

	companyName = "アンダーズ株式会社"

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true
