baseURL = "https://andaze.github.io/WebCorporate/"

languageCode = "ja-JP"
DefaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true

title = "My New Hugo Site"
theme = "andaze"
disableKinds = ["taxonomy", "term"]
assetDir = "/assets"
publishDir = "docs"
canonifyurls = true

[Languages]
[Languages.ja]
languageName = "JP"
weight = 1
languageCode = "ja-JP"
footerFacebookTitle = "公式フェイスブック"
footerPrivacyText = "プライバシーポリシー"
footerSocialMediaPrivacyText = "ソーシャルメディアポリシー"
footerSiteMapText = "サイトマップ"

[Languages.en]
languageName = "EN"
weight = 2
languageCode = "en-us"
footerFacebookTitle = "Official Facebook"
footerPrivacyText = "Privacy Policy"
footerSocialMediaPrivacyText = "Social Media Policy"
footerSiteMapText = "Site Map"

[params]
	JS = "/js/main.js"
	headerLogo = "img/yoko_c2.png"
	footerLogo = "img/yoko_2w.png"

	companyName = "アンダーズ株式会社"

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[[Languages.en.menu.main]]
name    ="company"
url     ="company"
weight = 1
[[Languages.en.menu.main]]
name    = "service"
url     = "service"
weight  = 2
[[Languages.en.menu.main]]
name    = "ir"
url     = "ir"
weight  =  3
[[Languages.en.menu.main]]
name   = "esg"
url    = "esg"
weight = 4
[[Languages.en.menu.main]]
name   = "news"
url    = "news"
weight = 5
[[Languages.en.menu.main]]
name   = "recruit"
url    = "recruit/top"
weight = 6
[[Languages.en.menu.main]]
name   = "contact"
url    = "contact"
weight = 7


[[Languages.ja.menu.main]]
name    ="会社情報"
url     ="company"
weight = 1
[[Languages.ja.menu.main]]
name    = "サービス"
url     = "services"
weight  = 2
[[Languages.ja.menu.main]]
name    = "IR情報"
url     = "ir"
weight  =  3
[[Languages.ja.menu.main]]
name   = "サステナビリティ"
url    = "esg"
weight = 4
[[Languages.ja.menu.main]]
name   = "ニュース"
url    = "news"
weight = 5
[[Languages.ja.menu.main]]
name   = "採用情報"
url    = "recruit/top"
weight = 6
[[Languages.ja.menu.main]]
name   = "お問い合わせ"
url    = "contact"
weight = 7
